### PR TITLE
Fixes issue with root and children

### PR DESCRIPTION
**Pull request by speercy**
## Description

This PR fixes an issue where attempting to duplicate an entry in a collection that has `root: true` would throw the error "Root page cannot have children"

## Explanation

The Gentlemen changed the CollectionTree in [Navigation Blueprints #3941](https://github.com/statamic/cms/pull/3941/files#diff-530461d0d11ee83e368ef5399dce7a565c3a5c40690b42cddf8ef3e6c45a7f67) to include an id key of `entry`

### CODE REVIEW

**Comment by kristiana-s** [comment]
Would be great to have this merged. Getting this issue on a client site where they duplicate pages often

**Comment by duncanmcclean** [comment]
I'll review this pull request this evening, after work. I didn't have any time last night.

**Comment by duncanmcclean** [comment]
@speercy I've just pulled this down to test. However, when I try with the fix, it causes an error:

image

And when I remove the `['entry']` bit, the error goes away and it works as expected. Maybe there's something I'm missing?

**Comment by speercy** [comment]
Which version of Statamic are you using? As noted in the initial explanation, this is to fix a pretty recent change in the Statamic code. I could change the fix to include a conditional that checks to see if the array has an `entry` key?

**Comment by duncanmcclean** [comment]
> Which version of Statamic are you using? As noted in the initial explanation, this is to fix a pretty recent change in the Statamic code. I could change the fix to include a conditional that checks to see if the array has an `entry` key?

Doink. I'm stupid, was on 3.1. I'll update to 3.2 and try again! Sorry

**Comment by duncanmcclean** [comment]
Gotcha, works fine for me on Statamic 3.2. I'll make 3.2 the minimum version.

**Comment by duncanmcclean** [comment]
Fixed in [v2.0.0](https://github.com/doublethreedigital/duplicator/releases/tag/v2.0.0)

**Pull request merged**
